# Generated by Django 2.2 on 2022-01-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_created=True, auto_now=True)),
                ('updated_on', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'ACTIVE')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
