# Generated by Django 2.2 on 2022-01-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220106_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('food', 'Food'), ('news', 'News'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('fashion', 'Fashion'), ('personal', 'Personal')], max_length=50, null=True),
        ),
    ]
